spring:
  application:
    name: gemini-gateway
  profiles:
    active: dev
    include: cloud
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://docker-server:3306/gemini_gateway?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  data:
    redis:
      host: docker-server
      port: 6379
      database: 7
      timeout: 10000
  cache:
    type: redis
    redis:
      cache-null-values: true
      key-prefix: "gemini-gateway:cache:"
      time-to-live: 1000
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

gemini:
  open-api:
    enabled: true
    info:
      version: "0.0.1-SNAPSHOT"
      title: "Gemini Gateway Boot"
      description: "网关服务"
      contact:
        name: "Gemini Gateway"
        email: "gemini@glseven.com"
        url: "https://www.glseven.com"
  gateway:
    ignore-urls:
      - /v3/api-docs/**
      - /webjars/**
      - /swagger-ui.html
      - /actuator/**
      - /*/v3/api-docs/**
      - /gemini-uaa/**
server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.security: debug